os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"
  - "/^v.*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - BRANCH=${TRAVIS_BRANCH}
  - TAG=${TRAVIS_TAG}
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: MRo4QUqkU3+wXcCchuMlE9LmsktJmoSHA7NiGMzy5H4ywx0nubqq7GIHJ9+V9a6Hj0XfGXuUoud5SgU0EXYcBfRkyEiEJTHXOXLPCtBsaDOfQ9y0P8b6EVhPT5BZEzAPb9yFNJJFBKN5C3BMSu5bn/s5/9PPxltDz/zv81dLA9mXQIXyQi4JPQofSQQhoxF4VZaz0OdcEgDRJT/Km99OT4oOt2AjLHh4EWv2s8bYoCXKOaVhQNeko5Kif7Je49saPs2lOzcH05cba/d304i/by7s1MwDb912Qz7i4O8xZP86YwMENCriz2uAH0VUGQwtyLkQczltjfqGkm+6KXYRVds+D7oONMIhVaEncH6A0fBsVuLTgz7/LM9j6mzfxY40jNxvhqRSDgCDE32ZiFrFeDSPvdip0DpknEYka01o2BMTKZFijaQuDns8ItK0wRUNsiiFVb/AkbblIjV6lhhXUk3ZjiCi9XOGa/9h7tiEGQPz86EximQWJeYgCOELLfFEgmyFTYABaEEqaFgyPSvm+6PQUy/AL9TA/5hGCNCKGog84o7j0C7ovE3kvLq75j20F8fLJLpdLZHMP0sCyRFT2x2fgz2rNrUPzAiirFvgyyg1bzHhDkxqRuMZ3sBQkRMUwN74CF/04PPvCyfMWoE9n1U+G3GI+//zrzYw9yxcoh4=
  - secure: V4FzC96beqvx3j+sxCfoi6ljuCPhiuF5NeJAUkF5zGDk+OJdo4nqqaee30WNPqAz+ULQXNEm/7A9rfUfrhQ1CxriJGWmBVNpXfYEO9ePVHcNIjbx4g71/NKe0ZBfwOOJzq0iRITrDCYJJxkzT83YP8ErGC/IJgK36d+JrqmrX+21V99pg030wBPGZZdo71mnZlxX/ahIvwrRaXdS1uaJHNT2T1w+11+sl6D6mnJddVVlzI6yZ4jI9cL1OD/dB0h+iQoaM1U4mzdYi3t+jILsWdJQIxb7gTQ8on+p0zC9x4iQM9f6SOgrQOadWwYPKC33SzbpNUEHSYYGa2Dxj5JY/IEbcnRGKoRMff0KQbTKU1XTysRKTl9bbZtzH00Ml8tUXhmQlhblDAVtoBftbHnVeAQnVfVpsW22Db/q1NWpd1pge+zq8LCusT37BowGEXXCq5Z41udt4cfe3EA+0MwnKPhB5lU39WASFytIYS+nNzp4CHZ79B55y/5ygDx1Y2hStLtxXnGaNwc6veVmTEnsr7ocgwnQwU1c447xaRVoZFKtauDhN1nFT5Udk7TTYWe9T1XOensXxs0fbnv0Z6e+WVG6jbmEMamjNqgyyHGiTRatlH06AnbEBKxmjnBEMeBFpSnX2uVZjevnGmYNpI0D1JDM5/w0rmr903+3EzNm9FU=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE}:${BRANCH} .
script: skip
after_success:
- if [[ -z "${TAG}" ]]; then echo "This commit hasn't been tagged, will not be pushed
  to dockerhub"; exit 0; fi
- docker --version
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker tag ${IMAGE}:${BRANCH} ${DOCKERHUB}/${IMAGE}:${TAG}
- docker push ${DOCKERHUB}/${IMAGE}:${TAG}
- echo "${DOCKERHUB}/${IMAGE}:${TAG}"
notifications:
  email:
    on_success: never
    on_failure: never
