os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v[0-9].*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: OAjIV55ABTILH1U59ja3VZl+17mElk8YIn+uf6z25EOv85/JEkG0FosrXDBDWztRHXkVwHZybYOGykjkoU1llG77/9Xh21wZqx61y7rf5hQujTaSWFRPdSSTGS1rfT/5iSkANFUhKM+7zJ4gVNJGdfc38pFYum/0mNpk3X5T1RDt5tEDSO+c/rISfZAwj1NaQDnXk89/txiqwRUHuKYhUcFJiGTo7Z8w6Bpjik3FA5X518TDZNSiwh1XfNqRFURKP2r1JPKmd71SWPEEIo6jOtU8NNJCe+6ShHo/DKXvMt4EEO1gIpqm8kRPnt8Bvsbw/1Uyn28JAnSGJk5AKS11gHynPK97zBUd6Lh2WFZjBrPJwmUfFmpJpBep7xtUtcBo+8t0vc7h5fbIKMfUL0v0SBL4ToD5G41h/sYxPZJfmirVwFAtiunQQZ4NLCqDe3DJ/nWnOOLbnN07nBHLQyjsNj4N6BesFsdN2YfnjRDvOi9Z3NtHJ6dbegnKZjoYEwi956UixiZtNY8a41/zsHupHa2gAy4HJ0hy9+ta1+lpkWf0pdsQCRzZb+AogcaOiBJWQs7w8VsRc479tdO3Q4n14Dk0aTk2YN2HuaWXES82Z8W1SaELONVfZ1t568alpyWGCsUPqg2LgSlfJ6L3Cv8MD9wSDYYrqT9UDovFiUeqtuc=
  - secure: FaVV9ELhGyhylLCUMiorGwpTDITRME+TdAo4S4oo/Q3xx1Q8Oo+DGdIzel7AXoxxMK1rgAg03X0dQ0fpQDoMqt3U894DHBa5fLjRkmAHBIKvbcA1rlS6XQtGK33ntrR4gnsR47lYZgCShJRKxbxCSGCcKdeNvdQKH366Ly/mmMPkD6uDvc7SBbdHFBOyQRjiN65a/f8RzbDI404duX6MBCUze+1kuIURZhITyRIjmcOqtcbImqBT41tQfKs4v5pnojVRtCCYprW0jMXWCOcA2ai3czp70QojKA85o+w5ilPA2bU95Pz7fCj+K5YEnOpov7sR/j8uzL96x3KGgmM3RL8sKS0103CVzFU8KmXl6MaDZ2qPHcoMVP55z6riKvt/XsFmnHKuLRjhHVqogap3ruW5yiGeXpw9zz/3CEf169yWTLTgMr/qsFUoO3q1VvixYAfTF/pdI6FpVe7XXFH+a2SY6DSr85WYG3xSua9WQawlYQd6F1dAf6HPWKO3jITw1I7aY67fbYSY9vNM+HJj3ASWCigZ9k9fy84WROqSBjwc26a/TXScIkaPU4c2x2EaYDdSmaxgMHHPeux6mMNHBrBSRZxF7/U4bvUtJu/4O6lw3n/Sd91EP5to8y4OJaUd1YwLjYh7Ggyx/E57kOCkkym7cUUPBPyh1OonGlIBi4Y=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE} .
script: skip
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- if [[ "${TRAVIS_BRANCH}" == *test* ]]; then docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER};
  docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}; echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}";
  else docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}; docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH};
  echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}"; fi
notifications:
  email:
    on_success: never
    on_failure: never
